stages:
  - if-UI-acceptence-test

if-UI-acceptence-test:
  image: node:17-alpine
  stage: if-UI-acceptence-test

  script:
    - apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main
    - yarn install
    - yarn start
